### ISSUE TITLE
Minecraft freezes / hangs on log message "[com.chattriggers.ctjs.launch.plugin.CTJSTransformer:makeTransformers:48]: Did not find frames+" (Ubuntu 20.10)

### ISSUE THREAD

**Issue by TheLegendOfKitty** [ChatTriggers/ChatTriggers#212]
System information:
16 gb ddr4, 3200 
Intel® Core™ i9-9900K CPU @ 3.60GHz × 16 
NVIDIA Corporation TU104 [GeForce RTX 2080 Rev. A]
Ubuntu 20.10, x64
GNOME 3.38.1, X11
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.10-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
Jvm args: ``-Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M``
Minecraft information:
Mods: https://digestedmosquito-staticassets.s3-us-west-2.amazonaws.com/mods.zip
Log: https://gist.github.com/TheLegendOfKitty/fd16d92716d314b87b01b6485d71432f
Ct modules: (cannot send files because they contain api keys)
averageAH
Colorizer
CustomTabCompletions
DeepEquals
DragonPercent
DungeonUtilities
Elementa
ExperimentationTable
numeralJS
PersistentData
PersistentVariables
PrivateChat
Promise
QuitCommand
request
RingSelector
SBInvSee
SettingsManager
slothpixel
soopyAddons

1.8.9-forge1.8.9-11.15.1.2318-1.8.9

**Comment by FalseHonesty** [comment]
Have you set your minecraft installation configuration to point to your own Java 8 Runtime, rather than the packaged version?

**Comment by TheLegendOfKitty** [comment]
Yep. Points to /usr/bin/java and running the executable with -version says it is java 8

**Comment by FalseHonesty** [comment]
Not 100% sure if this is the issue, but try installing a lower patch version of j8, I use 221, so perhaps give that a shot.

**Comment by TheLegendOfKitty** [comment]
where the hell do i get that without giving oracle my personal details

**Comment by dylann123** [comment]
i had this on windows, so this might not be helpful, but i just saved the modules to a temporary folder, deleted the chat triggers folder in config, and launched mc, then put the files back in.

**Comment by DJtheRedstoner** [comment]
> i had this on windows, so this might not be helpful, but i just saved the modules to a temporary folder, deleted the chat triggers folder in config, and launched mc, then put the files back in.

In this case you were having a different issue where the game hangs when the server is offline which it just was.

**Comment by Arti-Dev** [comment]
Issue should be resolved by now most likely, was having it earlier but not anymore
I believe it was caused by the downtime that was resolved at 8:54 AM EST today..

**Comment by TheLegendOfKitty** [comment]
> Issue should be resolved by now most likely, was having it earlier but not anymore
> I believe it was caused by the downtime that was resolved at 8:54 AM EST today..

uh what?

**Comment by FalseHonesty** [comment]
> uh what?

This is in reference to an issue different than what you encountered. Unfortunately, the conflict with Ubuntu's Java >221 still exists, and will continue to exist for the foreseeable future.

**Comment by TheScwumbler** [comment]
> Not 100% sure if this is the issue, but try installing a lower patch version of j8, I use 221, so perhaps give that a shot.

What Forge version do you use, and did you use 8u221 to install forge as well? 
I tried adding the executable path of jre 8u221 to the version settings but it crashes on launch. I figured this was a problem with the java version used to install forge and using a different version to launch it, so i tried to install forge with 221 and it failed with:

Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib/jvm/jre1.8.0_211/lib/i386/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at java.awt.Toolkit$3.run(Toolkit.java:1636)
	at java.awt.Toolkit$3.run(Toolkit.java:1634)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1670)
	at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:611)
	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:147)

Maybe I need to use a different forge version that is compatible with older java builds or something (?).

**Comment by TheLegendOfKitty** [comment]
#01f2a38 fixed this issue
