### ISSUE TITLE
Display background and align don't take into account bold text

### ISSUE THREAD

**Issue by Dolphin0xyz** [ChatTriggers/ChatTriggers#223]
When text in a display is bold, the background is not large enough and it is not aligned correctly
Aligned Right: [https://i.imgur.com/n0dJxv3.png](https://i.imgur.com/n0dJxv3.png)

**Comment by camnwalter** [comment]
Pretty sure this was fixed in 1.3.1 as `Renderer#getStringWidth` now always returns the formatted width

**Comment by Dolphin0xyz** [comment]
Ok that was me being dumb and forgetting to update, but it is still not correct in 1.3.1 [https://i.imgur.com/wuTL5mJ.png](https://i.imgur.com/wuTL5mJ.png) <--this text is meant to be aligned right, but the bold line isn't far enough over.
